version: '3.8'

services:
  dispersed-connection:
    build: 
      context: ./dispersedconnection
    container_name: dispersed-connection
    networks:
      - dispersedconnection-network
    ports:
      - "8000:8000"
    depends_on:
      - melanoma-detector
      - sleep-cycle-predictor

  nextjs-frontend:
    build:
      context: ./frontend
    container_name: nextjs-frontend
    networks:
      - dispersedconnection-network
    ports:
      - "80:3000"
      - "443:3000"
    environment:
      - MELANOMA_API_URL=http://melanoma-detector:8000/predict
      - SLEEP_API_URL=http://sleep-cycle-predictor:8002/predict
    depends_on:
      - dispersed-connection
      - melanoma-detector
      - sleep-cycle-predictor

  melanoma-detector:
    build: 
      context: ./skinDispersed
    container_name: melanoma-detector-fastapi
    networks:
      - dispersedconnection-network
    ports:
      - "8001:8000"

  sleep-cycle-predictor:
    build: 
      context: ./sleepQuality
    container_name: sleep-cycle-predictor-fastapi
    networks:
      - dispersedconnection-network
    ports:
      - "8002:8002"

networks:
  dispersedconnection-network:
    driver: bridge

