version: '3.8'

services:
  dispersed-connection:
    build: 
      context: ./dispersedconnection
    container_name: dispersed-connection
    networks:
      - dispersedconnection-network
    ports:
      - "80:80"
      - "443:443"
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME:-}
      - SSL_EMAIL=${SSL_EMAIL:-}
      - DJANGO_DB_PATH=${DJANGO_DB_PATH:-/data/db.sqlite3}
      - DJANGO_MEDIA_ROOT=${DJANGO_MEDIA_ROOT:-/data/media}
    depends_on:
      - melanoma-detector
      - sleep-cycle-predictor
    volumes:
      - ${DATA_VOLUME_PATH:-./dispersedconnection/data}:/data

  melanoma-detector:
    build: 
      context: ./skinDispersed
    container_name: melanoma-detector-fastapi
    networks:
      - dispersedconnection-network
    ports:
      - "8001:8000"

  sleep-cycle-predictor:
    build: 
      context: ./sleepQuality
    container_name: sleep-cycle-predictor-fastapi
    networks:
      - dispersedconnection-network
    ports:
      - "8002:8002"

networks:
  dispersedconnection-network:
    driver: bridge
